[ModelFeatures]
# features derived from our database i.e pssm_score
pssm_score


[WholePromoter]
# features derived from calculations over all the nucleotides of the promoter as one unit
# i.e promoter_strength, entropy
promoter_strength
promoter_zones_strength
dG_and_Tx


[Motifs]
# features from motifs.py file such as 'ada'
ada
araC
arcA


[DenovoMotifs]
# features from denovo_motifs.py file such as 'GTAAACTGCT'
GTAAACTGCT
TGCGCGTATG
TTTCAATCCT
TCMCTCCTTT


[NucleotidesRelations]
# features of the nucleotides relations such as 'gc_content', 'mono_mono_k_gap'
pseudo_knc = [ACG_frequency, CGCT_frequency]
z_curve = [z_curve_x, z_curve_y, z_curve_z]
gc_content
cumulative_skew = [gc_skew, at_skew]
at/gc_ratio
mono_mono_k_gap = [A__A, G_A, C__T]
mono_di_k_gap = [A__GA, G___TT]
mono_tri_k_gap = []
di_mono_k_gap = []
di_di_k_gap = []
di_tri_k_gap = []
tri_mono_k_gap = []
tri_di_k_gap = []


[OneHotEncoding]
# contains all the features derived from one_hot_encoding: contains 4x(promoter's length) features
# i.e 'A_-3', 'G_-24'
A_-3
G_-24
T_-17

