RNAI_RNAP_seq_dict = {
    "RNAP_promoter": {
        "forward": "TTGAGATCCTTTTTTTCTGCGCGTAATCTGCTGCTT",
        "reverse_complememt": "AAGCAGCAGATTACGCGCAGAAAAAAAGGATCTCAA",
    },
    "RNAI_promoter": {
        "forward": "TTGAAGTGGTGGCCTAACTACGGCTACACTAGAAGA",
        "reverse_complememt": "TCTTCTAGTGTAGCCGTAGTTAGGCCACCACTTCAA",
    },
    "RNAI_seq": {
        "forward": "AACAGTATTTGGTATCTGCGCTCTGCTGAAGCCAGTTACCTTCGGAAAAAGAGTTGGTAGCTCTTGATCCGGCAAACAAACCACCGCTGGTAGCGGTGGTTTTTTTGTTTGCAAGCAGCAGATTACGCGCAGAAAAAAAGGATCTCA",
        "reverse_complememt": "TGAGATCCTTTTTTTCTGCGCGTAATCTGCTGCTTGCAAACAAAAAAACCACCGCTACCAGCGGTGGTTTGTTTGCCGGATCAAGAGCTACCAACTCTTTTTCCGAAGGTAACTGGCTTCAGCAGAGCGCAGATACCAAATACTGTT",
    },
    "RNAP_seq": {
        "forward": "GCAAACAAAAAAACCACCGCTACCAGCGGTGGTTTGTTTGCCGGATCAAGAGCTACCAACTCTTTTTCCGAAGGTAACTGGCTTCAGCAGAGCGCAGATACCAAATACTGTTCTTCTAGTGTAGCCGTAGTTAGGCCACCACTTCAAGAACTCTGTAGCACCGCCTACATACCTCGCTCTGCTAATCCTGTTACCAGTGGCTGCTGCCAGTGGCGATAAGTCGTGTCTTACCGGGTTGGACTCAAGACGATAGTTACCGGATAAGGCGCAGCGGTCGGGCTGAACGGGGGGTTCGTGCACACAGCCCAGCTTGGAGCGAACGACCTACACCGAACTGAGATACCTACAGCGTGAGCTATGAGAAAGCGCCACGCTTCCCGAAGGGAGAAAGGCGGACAGGTATCCGGTAAGCGGCAGGGTCGGAACAGGAGAGCGCACGAGGGAGCTTCCAGGGGGAAACGCCTGGTATCTTTATAGTCCTGTCGGGTTTCGCCACCTCTGACTTGAGCGTCGATTTTTGTGATGCTCGTCAGGGGGGCGGAGCCTATGGAAA",
        "reverse_complememt": "TTTCCATAGGCTCCGCCCCCCTGACGAGCATCACAAAAATCGACGCTCAAGTCAGAGGTGGCGAAACCCGACAGGACTATAAAGATACCAGGCGTTTCCCCCTGGAAGCTCCCTCGTGCGCTCTCCTGTTCCGACCCTGCCGCTTACCGGATACCTGTCCGCCTTTCTCCCTTCGGGAAGCGTGGCGCTTTCTCATAGCTCACGCTGTAGGTATCTCAGTTCGGTGTAGGTCGTTCGCTCCAAGCTGGGCTGTGTGCACGAACCCCCCGTTCAGCCCGACCGCTGCGCCTTATCCGGTAACTATCGTCTTGAGTCCAACCCGGTAAGACACGACTTATCGCCACTGGCAGCAGCCACTGGTAACAGGATTAGCAGAGCGAGGTATGTAGGCGGTGCTACAGAGTTCTTGAAGTGGTGGCCTAACTACGGCTACACTAGAAGAACAGTATTTGGTATCTGCGCTCTGCTGAAGCCAGTTACCTTCGGAAAAAGAGTTGGTAGCTCTTGATCCGGCAAACAAACCACCGCTGGTAGCGGTGGTTTTTTTGTTTGC",
    },
}

RNAI_RNAP_dict = {
    "RNAI_seq": RNAI_RNAP_seq_dict["RNAI_seq"],
    "RNAP_seq": RNAI_RNAP_seq_dict["RNAP_seq"],
}
RNAI_RNAP_promoters_dict = {
    "RNAI_promoter": RNAI_RNAP_seq_dict["RNAI_promoter"],
    "RNAP_promoter": RNAI_RNAP_seq_dict["RNAP_promoter"],
}
promoter_seq_mapping = {"RNAI_promoter": "RNAI_seq", "RNAP_promoter": "RNAP_seq"}

# Current null model (other strand) as a lower bound threshold for alignment:
puc19_alignment_score_threshold = {
    "RNAP_promoter": 106.0,
    "RNAI_promoter": 102.0,
    "RNAI_seq": 369.0,
    "RNAP_seq": 1272.0,
}

# Max score of alignment (as an upper bound threshold for alignment):
puc19_alignment_max_score = {
    "RNAP_promoter": 180.0,
    "RNAI_promoter": 180.0,
    "RNAI_seq": 735.0,
    "RNAP_seq": 2765.0,
}

